In [1]:
#!/usr/bin/env python
# coding: utf-8

# 1. Update Pip Version

In[1]:

In [2]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


# 2. Installing Numpy Package

In[2]:

In [3]:
pip install numpy

     ---------------------------------------- 14.7/14.7 MB 7.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


# 3. Creating Array Object

In[3]:

In [4]:
import numpy as np

# 4. Create Numpy Array from data

In[4]:

In [5]:
python_list = [1, 2, 3, 4]

In[5]:

In [6]:
python_list

[1, 2, 3, 4]

In[6]:

In [7]:
x = np.asarray(python_list, dtype=np.float32) # Numpy array from python list (float)

In[7]:

In [8]:
x

array([1., 2., 3., 4.], dtype=float32)

In[8]:

In [9]:
x = np.asarray(python_list, dtype=np.uint32) # Numpy array from python list (int)

In[9]:

In [10]:
x

array([1, 2, 3, 4], dtype=uint32)

In[10]:

In [11]:
x = np.asarray([[1, 2],[3, 4]], dtype=np.float32) # 2-D Numpy array

In[11]:

In [12]:
x

array([[1., 2.],
       [3., 4.]], dtype=float32)

In[12]:

In [13]:
x = np.asfortranarray([[1, 2], [3, 4]], dtype=np.float32) # Implemented using Fortran order

In[13]:

In [14]:
x

array([[1., 2.],
       [3., 4.]], dtype=float32)

In[14]:

In [15]:
x.flags # F_CONTIGUOUS is True (elements are aligned in Fortran way)

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# 5. Creating Numpy Array filled with specific values

## 5.1 Creating Numpy Array filled with zeros

In[15]:

In [16]:
np.zeros(10) # All zero array with shape (N,)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In[16]:

In [17]:
np.zeros((10, 10)) # All zero 2-D array with shape (N,M)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In[17]:

In [18]:
np.zeros((5,5,5)) # All zero 3-D array with shape (N,M,K)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In[18]:

In [19]:
np.zeros((5,5,5)).shape

(5, 5, 5)

In[19]:

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In[20]:

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In[21]:

In [22]:
x

array([[1., 2.],
       [3., 4.]], dtype=float32)

In[22]:

In [23]:
x.shape

(2, 2)

## 5.2 Creating Array with the same shape

In[24]:

In [24]:
np.zeros(x.shape) # creating all-zero with the same shape (method1)

array([[0., 0.],
       [0., 0.]])

In[25]:

In [25]:
np.zeros_like(x) # creating all-zero with the same shape (method2)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In[28]:

In [26]:
np.ones_like(x) # creating all-one with the same shape 

array([[1., 1.],
       [1., 1.]], dtype=float32)

In[ ]:

In[29]:

In [27]:
np.eye(5) # I matrix (identity matrix) with shape (N,N)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In[31]:

In [28]:
np.identity(5) # I matrix (identity matrix) with shape (N,N)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In[32]:

In [29]:
np.eye(10,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In[33]:

In [30]:
np.eye(5,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In[34]:

In [31]:
np.ones(5)*3 # get all-constant array with shape (N,)

array([3., 3., 3., 3., 3.])

In[35]:

In [32]:
np.full((5,10),3,dtype=np.float32) # get all-constant array with shape (N, M)

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]], dtype=float32)

In[37]:

In [33]:
np.full_like(x, 5) # get all-constant array with the same shape

array([[5., 5.],
       [5., 5.]], dtype=float32)

# 6. Python range and Numpy Range, Linspace and Logspace

In[39]:

In [34]:
list(range(10)) # 0-9 integers (python_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In[40]:

In [35]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In[44]:

In [36]:
type(range(1,10))

range

In[41]:

In [37]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In[45]:

In [38]:
np.arange(10) # 0~9 integer (numpy)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In[43]:

In [39]:
np.arange(1,10) # 1~9 integers (numpy)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In[46]:

In [40]:
np.arange(1,10,2) # (start, end , step)

array([1, 3, 5, 7, 9])

In[48]:

In [41]:
np.arange(1.2,2,0.01)

array([1.2 , 1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 ,
       1.31, 1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41,
       1.42, 1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52,
       1.53, 1.54, 1.55, 1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63,
       1.64, 1.65, 1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74,
       1.75, 1.76, 1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85,
       1.86, 1.87, 1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96,
       1.97, 1.98, 1.99])

In[49]:

In [42]:
np.linspace(0.0,10.0,100) # divide [0.0, 10.0] space linearly by 100 numbers

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In[50]:

In [43]:
np.linspace(0.0, 10.0, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In[51]:

In [44]:
np.logspace(0.0, 10.0, 100) # divide [0.0, 10.0] space logarithmically by 100 numbers

array([1.00000000e+00, 1.26185688e+00, 1.59228279e+00, 2.00923300e+00,
       2.53536449e+00, 3.19926714e+00, 4.03701726e+00, 5.09413801e+00,
       6.42807312e+00, 8.11130831e+00, 1.02353102e+01, 1.29154967e+01,
       1.62975083e+01, 2.05651231e+01, 2.59502421e+01, 3.27454916e+01,
       4.13201240e+01, 5.21400829e+01, 6.57933225e+01, 8.30217568e+01,
       1.04761575e+02, 1.32194115e+02, 1.66810054e+02, 2.10490414e+02,
       2.65608778e+02, 3.35160265e+02, 4.22924287e+02, 5.33669923e+02,
       6.73415066e+02, 8.49753436e+02, 1.07226722e+03, 1.35304777e+03,
       1.70735265e+03, 2.15443469e+03, 2.71858824e+03, 3.43046929e+03,
       4.32876128e+03, 5.46227722e+03, 6.89261210e+03, 8.69749003e+03,
       1.09749877e+04, 1.38488637e+04, 1.74752840e+04, 2.20513074e+04,
       2.78255940e+04, 3.51119173e+04, 4.43062146e+04, 5.59081018e+04,
       7.05480231e+04, 8.90215085e+04, 1.12332403e+05, 1.41747416e+05,
       1.78864953e+05, 2.25701972e+05, 2.84803587e+05, 3.59381366e+05,
      

# 7. Create NumPy Array filled with values drawn randomly

In[52]:

In [45]:
np.random.rand(5)

array([0.80116299, 0.65753083, 0.08233429, 0.59129703, 0.6278273 ])

In[54]:

In [46]:
np.random.rand(5,5)

array([[0.27023712, 0.17524223, 0.92587902, 0.72312806, 0.49812078],
       [0.65554947, 0.38079921, 0.29666425, 0.41061159, 0.40812478],
       [0.85638611, 0.91920234, 0.32456319, 0.82351765, 0.45315001],
       [0.35350622, 0.93549381, 0.18068882, 0.80393002, 0.60480581],
       [0.47800694, 0.3881568 , 0.96868111, 0.5830255 , 0.77391395]])

In[56]:

In [47]:
np.random.randint(10)

8

In[57]:

In [48]:
np.random.randint(-5,5)

3

In[58]:

In [49]:
np.random.randn(5) # random number from normal distribution (Gaussian with mu=0, std=1) with shape (N,)

array([ 0.80809332, -1.03133657, -0.62202214, -0.81092299,  0.23392345])

In[59]:

In [50]:
np.random.randn(5,5)

array([[ 1.84429224,  1.02617055, -2.07806154,  1.12355504,  0.00688387],
       [ 0.01592999, -1.05924024, -0.03258755,  1.39914315,  0.09434145],
       [-0.56682922, -0.79178472, -1.44885655,  0.42631039,  1.1568815 ],
       [ 1.67543973,  0.09762322,  0.71973242, -0.78827403, -0.76237609],
       [ 0.29122718, -1.21901294, -2.19954262,  0.70082535,  0.83276012]])

In[ ]: